# Generated by Django 5.1.2 on 2024-12-17 14:43

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('avatar', imagekit.models.fields.ProcessedImageField(default='avatars/default.png', upload_to='avatars/%Y/%m/%d', verbose_name='头像')),
                ('name', models.CharField(default='A OUCer', max_length=8, verbose_name='名字')),
                ('intro', models.TextField(default='帅哥/靓女一枚', verbose_name='自我介绍')),
                ('weight', models.IntegerField(default=60, verbose_name='体重(kg)')),
                ('height', models.IntegerField(default=170, verbose_name='身高(cm)')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '保密')], default='unknown', max_length=8, verbose_name='性别')),
                ('address', models.TextField(default='中国海洋大学', verbose_name='地址')),
                ('email', models.EmailField(default='OUC@stu.ouc.edu.cn', max_length=254, verbose_name='邮箱')),
                ('sexPrefer', models.CharField(choices=[('male', '男'), ('female', '女'), ('both', '男女均可'), ('unknown', '未知')], default='unknown', max_length=8, verbose_name='性取向')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myBox.comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBox.profile')),
            ],
        ),
    ]
