# Generated by Django 5.1.2 on 2024-12-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBox', '0002_alter_comment_author_alter_comment_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
