# Generated by Django 5.1.2 on 2024-12-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBox', '0004_rename_created_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ver_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='验证码'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='邮箱是否已验证'),
        ),
    ]
