# Generated by Django 5.1.2 on 2024-12-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBox', '0005_profile_ver_code_profile_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('ver_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='验证码')),
                ('verified', models.BooleanField(default=False, verbose_name='邮箱是否已验证')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ver_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
