# Generated by Django 5.1.2 on 2024-12-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBox', '0006_email_remove_profile_email_remove_profile_ver_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
