# Generated by Django 5.1.2 on 2024-12-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBox', '0008_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Email',
            new_name='email',
        ),
    ]
